### ISSUE TITLE
Remove dependency on middlewares/utils (or at least make it optional)

### ISSUE THREAD

**Issue by slepic** [middlewares/cors#4]
I believe `middlewares/utils` package is only needed if the second parameter of the `Middlewares\Cors::__construct()` is not passed.

In my opinion passing null as the second parameter is just bad and should be deprecated anyway.
If you work with middlewares, you almost certainly already have a response factory instance laying around somewhere that you should just pass to the middleware.

**Comment by oscarotero** [comment]
Although I may agree, these middlewares packages try to cover different grades of integration:

- People that just want to drop a middleware that just work.
- People that want an easy and fast way to configure the factory and forget about it (in middlewares/utils you can to configure/register your own factory)
- People that want to pass a specific factory to every middleware (that's your case).

Depending of the framework/complexity of the project, people may prefer one or other.

**Comment by slepic** [comment]
According to dependency inversion and single responsibility principles, creating default dependencies is responsibility of a factory, not a constructor. IMHO, the library should enforce best practices which SRP and DIP certainly are. Now it seems to encourage the opposite...

So anyway, are you not in favour of making it optional dependency either (one that consumers have to install explicitely; throwing runtime exception if null is passed while the utils library is not installed)?

**Comment by oscarotero** [comment]
This change requires to release a major version, not only for this package but also all other packages in this organization.
I understand (and agree) with your position but I don't have time to do that, and don't see enough value of release a new major version that only remove features. So for now I'll keep it as is, but thanks for comment, I'll take it into account for the future.

**Comment by slepic** [comment]
ok thanks
